# Project-wide Gradle settings.
# IMPORTANT: This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Use this file to override default Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX package structure
android.useAndroidX=true
# Kotlin code style
kotlin.code.style=official
# Non-transitive R classes
android.nonTransitiveRClass=true
